# compose.yaml

services:
  php:
    build:
      context: .
    container_name: php-server
    restart: always
    ports:
      - "8080:80" # HTTP
      - "40443:443" # HTTPS
      - "40443:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "53306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  db_data:
  caddy_data:
  caddy_config:

